name: Documentation deploy

on:
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install Zensical
        run: pip install zensical

      - name: Build Documentation
        working-directory: docs-site
        run: zensical build --clean

      - uses: actions/configure-pages@v5

      - uses: actions/upload-pages-artifact@v5
        with:
          path: docs-site/site

      - id: deployment
        uses: actions/deploy-pages@v5