name: Documentation check

pull_request:
  paths:
    - "docs-site/**"

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install Zensical
        run: pip install zensical

      - name: Build Documentation
        working-directory: docs-site
        run: zensical build --clean